namespace DragoonMayCry.Audio.BGM
{
    public enum BgmId
    {
        Intro,
        CombatEnter1,
        CombatEnter2,
        CombatEnter3,
        CombatVerse1,
        CombatVerse2,
        CombatVerse3,
        CombatVerse4,
        CombatCoreLoop,
        CombatCoreLoopTransition1,
        CombatCoreLoopTransition2,
        CombatCoreLoopTransition3,
        CombatCoreLoopTransition4,
        CombatCoreLoopExit1,
        CombatCoreLoopExit2,
        CombatCoreLoopExit3,
        ChorusIntro1,
        ChorusIntro2,
        ChorusTransition1,
        ChorusTransition2,
        ChorusTransition3,
        Chorus,
        Chorus2,
        Chorus3,
        Riff,
        CombatEnd,
        Demotion,
        None,
    }
}
